app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Wont include all FOSUserBundle routes,
# becouse we need only login page.
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
