# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/person, role: ROLE_USER }
        - { path: ^/groups, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # This will enable API wsse security.
        # Security will use FOSUserBundle user account to validate.
        # There is a problem with password hash,
        # Becouse FOSUserBundle uses hash, we will need to give
        # that hash for person who will want to use API.
        # TODO: reanable
        #wsse_secured:
            #pattern:   ^/api/.*
            #stateless: true
            #wsse:      true

        main:
            anonymous: true

            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
